In [2]:
import pandas as pd
import numpy as np
from sentence_transformers import SentenceTransformer

df = pd.read_csv("dataset_july_20.csv")

In [13]:
def cosine_similarity(a: np.ndarray, b: np.ndarray):
    norm_product = np.linalg.norm(a) * np.linalg.norm(b)
    if norm_product == 0: return 0.0
    return float(np.dot(a, b) / norm_product)
    
def cosine_similarity_matrix(a: np.ndarray, b: np.ndarray):
    a_norm = a / np.linalg.norm(a, axis=1, keepdims=True)
    b_norm = b / np.linalg.norm(b, axis=1, keepdims=True)
    return a_norm @ b_norm.T

In [3]:
df.head()

,Timestamp,activity,category
0,7/20/2026 18:39:09,Bouldering,Sports
1,7/20/2026 18:39:11,I like reading webtoons,Reading/Books
2,7/20/2026 18:39:14,writing fiction,Reading/Books
3,7/20/2026 18:39:23,Voice Acting,Arts
4,7/20/2026 18:39:25,Hiking leads to a lot of fun and great scenic ...,Travel/Outdoors

In [5]:
model = SentenceTransformer("all-MiniLM-L6-v2")

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 8508.22it/s]

In [6]:
test = "I have been playing a lot of slay the spire 2, but I also like watching movies"

query_embedding = model.encode(test)

In [7]:
query_embedding

array([ 7.46441830e-04, -1.17444977e-01,  1.93057265e-02, -2.87953373e-02,
       -1.66335069e-02,  4.90937643e-02, -2.13475917e-02,  2.51526684e-02,
       -1.15175173e-02,  7.65543506e-02, -8.12005624e-02,  2.97904424e-02,
       -7.32403323e-02,  6.13542981e-02,  1.91979427e-02,  1.22904265e-03,
        8.32257122e-02, -1.01704989e-02,  4.04044203e-02, -1.78791359e-02,
       -2.60873437e-02, -8.27504694e-02,  3.34601314e-03,  3.68573004e-03,
        1.75228936e-03,  4.86323424e-03, -3.34928297e-02,  3.15295644e-02,
       -4.01305817e-02, -6.29237592e-02,  1.36301992e-02,  1.48234339e-02,
       -7.67658055e-02,  8.79065483e-04, -7.39687458e-02, -2.67362986e-02,
        6.17602691e-02, -1.31415948e-01, -1.48785889e-01, -4.97323759e-02,
        3.55797657e-03,  1.18162990e-01,  3.15009281e-02, -2.28327848e-02,
       -1.65702626e-02, -7.47936368e-02, -3.29869948e-02, -3.95417511e-02,
        4.77824584e-02,  4.39064465e-02,  3.56721282e-02, -5.51759964e-03,
       -7.19268993e-03, -4.13510911e-02,  5.15918359e-02,  4.18217033e-02,
       -1.51093761e-02,  4.35269736e-02,  4.03258540e-02, -4.17487361e-02,
        3.88351232e-02, -5.44491038e-02, -1.22383246e-02, -6.01375336e-03,
        1.78917013e-02, -1.93593800e-02,  4.07864116e-02,  4.60346267e-02,
        5.16648330e-02,  1.99582744e-02, -1.26511753e-01,  2.06760000e-02,
        3.49750593e-02, -5.52769452e-02,  3.53620714e-03, -1.09785795e-02,
       -4.93344851e-03, -1.16451800e-01,  4.25688084e-03, -5.53348940e-03,
        2.48717647e-02,  2.81032417e-02, -5.39658815e-02,  4.99807447e-02,
        7.40526756e-03, -3.03885099e-02, -6.16866210e-03,  2.03053914e-02,
       -5.84164970e-02,  2.13526115e-02,  2.54280623e-02,  2.06609853e-02,
       -2.55565215e-02,  9.85278636e-02, -5.92551986e-03,  9.63466428e-03,
        1.27030760e-02, -2.90561933e-02, -9.12228320e-03,  3.78607810e-02,
       -3.43435109e-02, -2.66343243e-02,  2.44927146e-02, -5.93375275e-03,
        2.32862569e-02,  3.18856686e-02,  3.77840549e-02,  5.11115156e-02,
        1.26496367e-02, -4.93368134e-02,  1.95444934e-03,  4.93284874e-02,
        1.62958615e-02,  1.95855517e-02,  2.55150702e-02,  1.06445581e-01,
        9.21898261e-02,  5.12718000e-02,  3.63729410e-02,  1.02780044e-01,
        5.17116524e-02,  4.16205563e-02,  1.16418684e-02,  1.67866908e-02,
        2.62409961e-03, -1.25588374e-02, -2.39266753e-02, -2.36602364e-33,
       -4.66780849e-02, -2.30475962e-02, -6.95779100e-02,  4.82860729e-02,
       -2.19780728e-02,  4.64159151e-04,  1.09608620e-02,  6.74679130e-02,
       -8.00576061e-02,  2.06056796e-02, -9.80888214e-03, -1.67541043e-03,
       -5.10136299e-02,  2.79428773e-02,  9.54485908e-02, -6.10686280e-02,
        2.09888183e-02,  4.31225114e-02, -6.65734289e-03, -3.17568369e-02,
        5.07874880e-03, -5.30278236e-02, -7.16112368e-03,  9.49679222e-03,
        1.66606270e-02, -3.49392891e-02, -1.35614807e-02, -8.26939046e-02,
        3.70960608e-02,  5.10642380e-02,  4.15625013e-02, -7.76247680e-03,
       -7.91771561e-02, -6.28595874e-02,  6.80608228e-02, -9.33219586e-03,
       -4.00852859e-02, -3.98400575e-02, -4.29101214e-02, -1.49532128e-02,
       -5.24474829e-02,  7.16117844e-02, -4.02470566e-02, -2.14705965e-03,
       -1.76763721e-02, -2.69981883e-02,  8.17967504e-02, -4.59554829e-02,
       -6.69770986e-02, -8.06499645e-03, -1.57725662e-02,  3.96047123e-02,
       -3.87577266e-02, -1.15061188e-02,  2.15193280e-03,  2.44150460e-02,
        3.66646945e-02, -2.77282912e-02,  7.99690932e-02, -6.80915341e-02,
        1.09894352e-03, -4.17243280e-02, -5.30033894e-02, -1.88163519e-02,
       -5.32454103e-02,  3.93725373e-02,  4.17083465e-02,  3.33172232e-02,
       -3.39592099e-02, -2.23252531e-02, -1.22184027e-03, -2.35707921e-04,
        5.58663607e-02,  1.89311784e-02, -2.09991653e-02,  2.56808195e-02,
       -9.97808948e-03,  9.20356158e-03, -1.14558963e-02,  1.53632658e-02,
       -4.03496623e-02, -1.44418497e-02, -2.05688123e-02,  2.17040288e-04,
        1.47496546e-02, -2.95552611e-02,  1.03585050e-02, -1.46458432e-01,
        4.51343432e-02,  1.55222332e-02, -4.30756658e-02, -1.04927652e-01,
        2.91336216e-02, -6.95090592e-02, -2.58191265e-02,  2.17929085e-33,
        4.71878089e-02, -1.40968353e-01, -2.70502996e-02, -4.95592803e-02,
       -2.43736506e-02,  1.38760190e-02, -8.22482109e-02, -8.05297960e-03,
        1.48656424e-02,  4.40194681e-02,  1.50766540e-02,  7.82100186e-02,
       -3.95858139e-02,  2.60248594e-02,  5.29779568e-02, -8.28232691e-02,
        4.89870552e-03, -2.96356250e-02,  7.18080774e-02,  1.17091537e-02,
        2.76293196e-02, -2.00449079e-02,  1.36062112e-02, -5.93693592e-02,
        9.45586935e-02, -4.26879106e-03, -7.72819296e-02,  9.91694164e-03,
       -1.24440547e-02,  1.54019063e-02,  5.04028052e-02,  6.37282133e-02,
       -4.66017686e-02, -6.44354969e-02, -3.77905346e-03,  4.91368361e-02,
        1.04932919e-01, -2.75052041e-02, -7.44092241e-02, -2.25996803e-02,
       -1.49720749e-02,  6.43204600e-02,  5.82288438e-03,  2.18640696e-02,
        9.52244252e-02,  2.14662831e-02,  5.45857660e-02,  3.65582556e-02,
       -8.54277313e-02,  8.58278200e-03, -2.71566659e-02,  5.57376444e-03,
        2.67528426e-02, -1.03207543e-01,  1.48754846e-02, -5.98720685e-02,
       -1.54239722e-02, -3.73791903e-02,  5.79924788e-03, -1.75922457e-02,
        4.90676686e-02,  4.61209333e-03, -1.07569978e-01,  3.12216301e-03,
       -9.45589272e-04,  4.50674817e-02, -6.45741075e-02,  2.17212494e-02,
       -5.91379181e-02, -2.22665239e-02, -1.46796122e-01, -4.76973057e-02,
       -8.88660029e-02, -1.28516359e-02, -8.28739107e-02, -7.20310137e-02,
        1.64475255e-02,  3.21302116e-02,  3.31108160e-02, -6.77966848e-02,
        4.02667113e-02,  6.35505375e-03,  7.36225992e-02, -8.39622784e-03,
        4.98058610e-02,  3.24068218e-02,  2.97291689e-02,  7.57623166e-02,
       -3.96379828e-03, -1.60792544e-02,  5.85911749e-03,  2.19778046e-02,
       -2.37320806e-03, -2.77326591e-02,  7.16359913e-02, -2.07605702e-08,
       -3.17062400e-02,  8.72102678e-02,  5.85000440e-02, -4.53896006e-04,
       -1.83061529e-02, -4.75975536e-02, -8.32169876e-02,  1.25093594e-01,
        2.62007378e-02, -3.40072252e-02,  1.80183016e-02, -9.35107246e-02,
       -1.39288977e-03, -4.50734384e-02,  1.50105119e-01,  1.06490880e-01,
        1.07307404e-01, -7.60695040e-02, -3.03248726e-02,  7.26952702e-02,
        4.38314974e-02,  6.91653267e-02,  5.24303317e-02,  1.14054736e-02,
       -9.18816552e-02,  5.62410355e-02,  3.94440703e-02, -1.07033230e-01,
        1.31622344e-01,  1.45138456e-02,  1.31793870e-02,  7.14978278e-02,
        1.71179399e-02, -3.33855152e-02,  3.28475200e-02,  3.87945510e-02,
        1.05670728e-01, -4.15569134e-02,  3.51222903e-02,  4.84504402e-02,
        6.04487434e-02,  4.54742694e-03,  4.59438786e-02,  5.27181029e-02,
       -1.79507844e-02,  8.03764164e-02,  9.96484235e-02, -9.53033343e-02,
        5.93864452e-03, -2.27119271e-02,  4.78653796e-02,  5.95968105e-02,
       -4.30806689e-02,  2.85283178e-02,  4.66982797e-02,  2.36544665e-03,
        2.77157463e-02,  5.62052941e-03, -2.97403205e-02, -1.05854180e-02,
        1.47104457e-01, -4.93135192e-02, -7.72400051e-02,  5.37644401e-02],
      dtype=float32)

In [8]:
texts = df["activity"].to_list()

In [9]:
document_embeddings = model.encode(texts)

In [10]:
document_embeddings

array([[-3.83439176e-02,  5.66874631e-02,  7.01797083e-02, ...,
        -1.17707536e-01,  1.51362857e-02, -5.27941175e-02],
       [-6.61628246e-02, -8.11682120e-02, -6.96940273e-02, ...,
         5.39536588e-02,  2.69803940e-03,  3.52379680e-02],
       [ 1.15028806e-02, -2.45191809e-02,  8.07629153e-02, ...,
         1.54281582e-03,  9.47718229e-03, -5.48374839e-02],
       ...,
       [-1.71456598e-02, -6.96660876e-02,  4.54195365e-02, ...,
         1.34385088e-02,  1.54708931e-02, -4.21309024e-02],
       [ 4.87561785e-02,  1.40169039e-02,  5.52156453e-05, ...,
         5.00839576e-02, -9.86676812e-02, -3.93462181e-02],
       [ 2.98440224e-03, -3.53777199e-04, -2.60574128e-02, ...,
         7.22838417e-02,  1.22647993e-02, -3.91820706e-02]],
      shape=(27, 384), dtype=float32)

In [ ]:
sims = cosine_similarity_matrix(query_embedding.reshape(1, -1), document_embeddings)[0]

In [17]:
results = df.copy()
results["similarity"] = sims

results = results.sort_values("similarity", ascending=False)

In [18]:
results

,Timestamp,activity,category,similarity
11,7/20/2026 18:40:36,Watching movies,Arts,0.550615
8,7/20/2026 18:40:12,I like to play games.,Gaming,0.432254
7,7/20/2026 18:40:06,I enjoy watching TV shows and discussing them ...,Arts,0.380731
9,7/20/2026 18:40:22,I like playing gacha games without spending mo...,Gaming,0.360670
24,7/20/2026 18:44:50,I enjoy watching horrible Tubi movies just to ...,Arts,0.360657
4,7/20/2026 18:39:25,Hiking leads to a lot of fun and great scenic ...,Travel/Outdoors,0.346487
5,7/20/2026 18:39:39,Golfing is my favourite activity.,Sports,0.345188
25,7/20/2026 18:45:02,I like going camping often.,Travel/Outdoors,0.340112
18,7/20/2026 18:42:04,i like going hiking when I have free time,Travel/Outdoors,0.307109
16,7/20/2026 18:41:01,I like to play ice hockey in the fall.,Sports,0.290431
1,7/20/2026 18:39:11,I like reading webtoons,Reading/Books,0.268784
12,7/20/2026 18:40:41,play rec league,Sports,0.266914
22,7/20/2026 18:44:25,Play Seven Deadly Sins Origins,Gaming,0.255525
19,7/20/2026 18:42:33,Reading books in a quiet place,Reading/Books,0.247264
13,7/20/2026 18:40:49,If given the option I would spend time working...,Arts,0.234907
23,7/20/2026 18:44:39,I love painting scenaries and walking art proc...,Arts,0.232596
17,7/20/2026 18:41:02,I like listening to music and dancing,Music,0.229540
20,7/20/2026 18:42:42,I like finding nice outdoor spaces with a lapt...,Reading/Books,0.227583
10,7/20/2026 18:40:32,I like to eat out at various restaurants.,Food/Cooking,0.183739
15,7/20/2026 18:40:56,Listen to different genres of music sequential...,Music,0.183389
0,7/20/2026 18:39:09,Bouldering,Sports,0.134034
2,7/20/2026 18:39:14,writing fiction,Reading/Books,0.129148
3,7/20/2026 18:39:23,Voice Acting,Arts,0.126867
21,7/20/2026 18:43:29,I love making pasta for myself and looking up ...,Food/Cooking,0.089246
14,7/20/2026 18:40:55,Coffee,Food/Cooking,0.014616
6,7/20/2026 18:39:56,I'd like to voice act in a properly treated vo...,Arts,0.013002
26,7/20/2026 18:45:30,Cooking,Food/Cooking,0.002997