In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("data/dramas.csv")

In [2]:
df.head(10)

,Unnamed: 0,name,content,no_of_reviews,no_of_viewers,aka_names,screenwriter,director,genres,tags,...,main_role,support_role,no_of_extracted_reviews,Total_sentences,POSITIVE_people_sentiment,POSITIVE_sentences,NEGATIVE_people_sentiment,NEGATIVE_sentences,reviewer_location_info,reviewer_gender_info
0,0,goblin,Kim Shin was once an unbeatable general in Gor...,464.0,198650.0,"쓸쓸하고 찬란하神-도깨비 , Dokkaebi , Sseulsseulhago Chal...",Kim Eun Sook,Lee Eung Bok,"Comedy, Romance, Fantasy, Melodrama","Supernatural, Older Man/Younger Woman, Intersp...",...,"Gong Yoo, Kim Go Eun, Lee Dong Wook, Yoo In Na...","Lee El, Kim Sung Kyum, Kim Byung Chul, Jo Woo...",422,6390,grim reaper - (sunny; bromance; shin; relation...,3226.0,"age gap - (lead; issue), grim reaper - (sunny)...",1331.0,"Counter({'': 238, 'usa': 14, 'united states': ...","Counter({'female': 318, '': 59, 'male': 44})"
1,1,strong woman do bong soon,"Do Bong Soon is a petite, unemployed woman who...",345.0,184710.0,"Himsseonyeoja Dobongsun , Powerful Woman Do Bo...",Baek Mi Kyung,Lee Hyung Min,"Action, Comedy, Romance, Supernatural","Strong Female Lead, Female Lead Action Scenes,...",...,"Park Bo Young, Park Hyung Sik, Kim Ji Soo","Jun Suk Ho, Shim Hye Jin, Yoo Jae Myung, Ahn W...",317,4615,female lead - (male; badass; amazing; characte...,2236.0,"serial killer - (plot; gangster), female lead,...",1235.0,"Counter({'': 197, 'united states': 10, 'usa': ...","Counter({'female': 228, '': 57, 'male': 32})"
2,2,weightlifting fairy kim bok joo,Bok Joo is a weightlifter who is pursuing her ...,267.0,167702.0,"Weightlifting Fairy Kim Bok-ju , Weightlifting...","Yang Hee Seung, Kim Soo Jin","Oh Hyun Jong, Nam Sung Woo","Comedy, Romance, Life, Sports","Friends To Lovers, Weightlifting, Strong Femal...",...,"Lee Sung Kyung, Nam Joo Hyuk, Lee Jae Yoon, Ky...","Cho Hye Jung, Lee Joo Young, Ji Il Joo, Yoo J...",246,3819,"love story - (character; beautiful), female le...",2139.0,"watch drama, female lead, male lead, character...",741.0,"Counter({'': 134, 'usa': 9, 'india': 4, 'phili...","Counter({'female': 176, '': 44, 'male': 26})"
3,3,descendants of the sun,A love story that develops between a surgeon a...,270.0,167287.0,"Taeyangeui Huye , The Sun's Descendants , Taey...","Kim Eun Sook, Kim Won Seok","Baek Sang Hoon, Lee Eung Bok","Action, Comedy, Romance, Melodrama","Hardworking Male Lead, Multiple Couples, Broma...",...,"Song Joong Ki, Song Hye Kyo, Jin Goo, Kim Ji Won","Lee Seung Joon, Seo Jung Yeon, Park Hwan Hee, ...",252,3728,"watch drama - (start; want; recommend), second...",1797.0,"watch drama - (time), female lead, last episod...",816.0,"Counter({'': 143, 'india': 8, 'usa': 6, 'unite...","Counter({'female': 193, '': 35, 'male': 24})"
4,4,w,"Oh Sung Moo, the father of cardiothoracic surg...",285.0,159860.0,"W – Two Worlds , W-두 개의 세계 , W – Two Worlds Apart",Song Jae Jung,Jeong Dae Yun,"Thriller, Comedy, Romance, Fantasy","Parallel Dimension, Gun Violence, Crossworlds ...",...,"Han Hyo Joo, Lee Jong Suk","Kim Eui Sung, Lee Tae Hwan, Jung Eugene, Lee S...",265,4664,"watch drama - (recommend), love story, really ...",1925.0,"second half - (drama), watch drama - (never), ...",1167.0,"Counter({'': 151, 'usa': 7, 'india': 6, 'phili...","Counter({'female': 196, '': 48, 'male': 21})"
5,5,what's wrong with secretary kim,The series revolves around the narcissistic Le...,243.0,159470.0,"What's Wrong With Secretary Kim? , Why Would S...","Baek Sun Woo, Choi Bo Rim",Park Joon Hwa,"Business, Comedy, Romance","Boss-Employee Relationship, Rich Male Lead, Ad...",...,"Park Min Young, Park Seo Joon","Lee Tae Hwan, Pyo Ye Jin, Kim Hye Ok, Kim Byun...",220,2998,"rom com - (best; great; really), side characte...",1414.0,"male lead, vice chairman, female lead, drama r...",751.0,"Counter({'': 123, 'united states': 5, 'usa': 5...","Counter({'female': 153, '': 45, 'male': 22})"
6,6,it's okay to not be okay,Moon Gang Tae is a community health worker at ...,558.0,156581.0,"Saikojiman Gwaenchanha , I'm a Psycho but It's...",Jo Yong,"Park Shin Woo, Jung Dong Yoon","Psychological, Comedy, Romance, Drama","Possessive Female Lead, Independent Female Lea...",...,"Kim Soo Hyun, Seo Yea Ji, Oh Jung Se","Park Gyu Young, Jang Young Nam, Kim Chang Wan,...",507,8719,mental health - (issue; different; topic; diso...,4717.0,mental health - (issue; disorder; deal; patien...,1623.0,"Counter({'': 333, 'usa': 9, 'canada': 6, 'indi...","Counter({'female': 371, '': 88, 'male': 48})"
7,7,crash landing on you,"After getting into a paragliding accident, Sou...",413.0,151890.0,"Salangui Bulsichag , Sarangui Bulsichag , Brea...",Park Ji Eun,Lee Jeong Hyo,"Military, Comedy, Romance, Political","North And South Korea, Strong Male Lead, Rich ...",...,"Hyun Bin, Son Ye Jin, Seo Ji Hye, Kim Jung Hyun","Yang Kyung Won, Lee Shin Young, Yoo Soo Bin, T...",368,5848,"love story - (forbidden), watch drama - (start...",3145.0,"watch drama, happy end, last episode, female l...",1150.0,"Counter({'': 230, 'usa': 12, 'india': 5, 'aust...","Counter({'female': 261, '': 71, 'male': 36})"
8,8,boys over flowers,Geum Jan Di comes from a poor family who owns ...,306.0,141661.0,"Boys Before Flowers , Kgotboda Namja , Kkotbod...",Yoon Ji Ryun,Jeon Ki Sang,"Comedy, Romance, Youth, Drama","Rich Man/Poor Woman, School Bullying, Love Tri...",...,"Gu Hye Seon, Lee Min Ho, Kim Hyun Joong, Kim B...","Kim So Eun, Lee Hye Young, Kim Jong Jin, Jang ...",288,4016,"watch drama - (say), love drama, fell love, re...",1559.0,"female lead, watch drama, joon pyo - (goo), ma...",1228.0,"Counter({'': 158, 'usa': 10, 'india': 6, 'braz...","Counter({'female': 214, '': 61, 'male': 13})"
9,9,the heirs,Kim Tan is the heir to Empire Group who has be...,251.0,140311.0,"The Inheritors , The One Trying to Wear the Cr...",Kim Eun Sook,"Kang Shin Hyo, Boo Sung Chul","Comedy, Romance, Drama, Melodrama","High School, Family Pressure, Love Triangle, S...",...,"Lee Min Ho, Park Shin Hye, Kim Woo Bin","Kim Ji Won, Kang Min Hyuk, Choi Jin Hyuk, Kang...",238,3711,"watch drama, story line, really good, high sch...",1331.0,"poor girl - (rich; fall; boy), female lead, wa...",1239.0,"Counter({'': 136, 'usa': 5, 'india': 4, 'austr...","Counter({'female': 179, '': 49, 'male': 10})"

In [3]:
df_users = pd.read_csv("data/users.csv")

In [4]:
df_users.head(10)

,user_id,gender,location,user_watch_history,preferred_genre,preferred_country
0,U000001,Female,Singapore,"[""chicago typewriter""]",Mystery,South Korea
1,U000002,Female,United States,"[""under the power"", ""memorist""]",Mystery,Japan
2,U000003,Female,United States,"[""come and hug me"", ""six flying dragons"", ""moo...",Fantasy,South Korea
3,U000004,Female,Canada,"[""the new employee"", ""oh! my emperor season 2""...",Comedy,South Korea
4,U000005,Female,Italy,"[""birth of a beauty"", ""untouchable"", ""legend o...",Comedy,China
5,U000006,Male,United Kingdom,"[""behind every star"", ""my girlfriend"", ""negoti...",Life,China
6,U000007,Female,Philippines,"[""what's wrong with secretary kim"", ""stranger ...",Youth,South Korea
7,U000008,Female,United States,"[""dear.m"", ""the universe\u2019s star"", ""gen y""...",Romance,South Korea
8,U000009,Female,United States,"[""go ahead"", ""put your head on my shoulder"", ""...",Comedy,South Korea
9,U000010,Female,Philippines,"[""i'm not a robot"", ""kahogo no kahoko"", ""orthr...",Drama,Japan