# Assignment 1: Exploratory Data Analysis (Twitch Viewership)

In [9]:
import pandas as pd
import numpy as np

df_sessions = pd.read_csv("data/sessions.csv")
df_streamers = pd.read_csv("data/streamers.csv")
df_streams = pd.read_csv("data/streams.csv")
df_viewers = pd.read_csv("data/viewers.csv")

## DF1: Sessions

In [13]:
df_sessions.dtypes

session_id              str
viewer_id               str
streamer_id             str
stream_id               str
started_at              str
ended_at                str
duration_mins         int64
chat_messages_sent    int64
bits_cheered          int64
followed_during        bool
subscribed_during      bool
dtype: object

In [19]:
print(df_sessions.shape)
print(df_sessions.describe())

(22825, 11)
       duration_mins  chat_messages_sent  bits_cheered
count   22825.000000        22825.000000  22825.000000
mean       59.051303            6.442629    398.425323
std        60.383979           46.576309   1571.528658
min         0.000000            0.000000      0.000000
25%        15.000000            0.000000      0.000000
50%        39.000000            1.000000      0.000000
75%        83.000000            5.000000      0.000000
max       443.000000         1987.000000  10000.000000

In [21]:
df_sessions.head(3)

,session_id,viewer_id,streamer_id,stream_id,started_at,ended_at,duration_mins,chat_messages_sent,bits_cheered,followed_during,subscribed_during
0,SES000001,VWR00938,STR0055,SM00860,2024-01-18 19:16:00,2024-01-18 20:28:00,72,0,0,False,False
1,SES000002,VWR00804,STR0034,SM00542,2024-01-04 17:11:00,2024-01-04 19:41:00,150,11,0,False,False
2,SES000003,VWR00704,STR0008,SM00124,2024-02-15 15:11:00,2024-02-15 16:53:00,102,5,0,False,False

## DF2: Streamers

In [6]:
df_streamers.dtypes

Streamers:

streamer_id                 str
streamer_name               str
category                    str
language                    str
partner_status             bool
total_followers           int64
avg_concurrent_viewers    int64
dtype: object

In [22]:
df_streamers.head(3)

,streamer_id,streamer_name,category,language,partner_status,total_followers,avg_concurrent_viewers
0,STR0001,xQc,Just Chatting,English,True,11500000,138706
1,STR0002,Pokimane,Just Chatting,English,True,-25551,71660
2,STR0003,HasanAbi,Just Chatting,English,True,2600000,34220

## DF3: Streams

In [7]:
df_streams.dtypes

Streams:

stream_id                  str
streamer_id                str
started_at                 str
ended_at                   str
stream_duration_hrs    float64
category                   str
peak_viewers           float64
title_has_hype_word       bool
was_raid                  bool
dtype: object

In [23]:
df_streams.head(3)

,stream_id,streamer_id,started_at,ended_at,stream_duration_hrs,category,peak_viewers,title_has_hype_word,was_raid
0,SM00001,STR0001,2024-02-14 18:00:00,2024-02-14 21:00:00,3.0,Just Chatting,108989.0,False,True
1,SM00002,STR0001,2024-01-28 18:00:00,2024-01-28 21:00:00,3.0,Just Chatting,51635.0,True,False
2,SM00003,STR0001,2024-01-31 09:00:00,2024-01-31 16:00:00,7.0,Just Chatting,212127.0,False,False

## DF4: Viewers

In [11]:
df_viewers.dtypes

viewer_id               str
age_group               str
country                 str
account_age_days      int64
subscription_tier       str
preferred_category      str
dtype: object

In [24]:
df_viewers.head(3)

,viewer_id,age_group,country,account_age_days,subscription_tier,preferred_category
0,VWR00001,18-24,AR,355,free,IRL
1,VWR00002,25-34,CA,1670,free,Creative
2,VWR00003,35-44,US,1108,free,Just Chatting